baseurl = "/"
languageCode = "en-us"

[menu]
    [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

    [[menu.main]]
    identifier = "festival"
    name       = "Festival"
    url        = "/festival/"
    weight     = 2

    [[menu.main]]
    identifier = "seriale-pro"
    name       = "Seriale Pro"
    url        = "/seriale-pro/"
    weight     = 3

    [[menu.main]]
    identifier = "program"
    name       = "Program"
    url        = "/program/"
    weight     = 4

    [[menu.main]]
    identifier = "speaker"
    name       = "Speaker"
    url        = "/speaker/"
    weight     = 5
    
    [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/post/"
    weight     = 7

    [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 8

[languages]
  [languages.en]
    title = "die seriale en"
    weight = 1
  [languages.de]
    title = "die seriale de"
    weight = 2